spring:
  application:
    name: yupao-bankend
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user
    username: root
    password:
  data:
    redis:
      host: localhost      # 只有一个就写这个
      port: 6379           # 只有一个，但写出来清晰
      password:            # 留空，但写出来说明“我没设密码”
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

